import type { Metadata } from "next";
import { Onest } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Sidebar from "@/components/Sidebar/Sidebar";
import Footer from "@/components/Footer/Footer";

const onest = Onest({
  subsets: ["latin"],
  variable: "--font-onest",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function getUserInfo() {
  const token = null;
  // const token = "1";

  const userRole = null;
  // const userRole = "admin";
  // const userRole = "user";
  return { token, userRole };
}

const { token, userRole } = getUserInfo();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${onest.className} antialiased`}>
        {(!token || userRole === "user") && <Navbar />}
        {userRole === "admin" && <Sidebar />}
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
